'use client';

import './globals.css'
import { Inter } from 'next/font/google'
import { useEffect } from 'react';
import AxeAccessibility from '../components/AxeAccessibility'
import NetworkModeToggle from '../components/NetworkModeToggle/NetworkModeToggle';
import { initializeNetworkInterceptor } from '../lib/network-interceptor';

const inter = Inter({ subsets: ['latin'] })

// The metadata export is not supported in a client root layout.
// This can be moved to a different file if needed.
// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  useEffect(() => {
    initializeNetworkInterceptor();
  }, []);

  return (
    <html lang="en">
      <body className={inter.className}>
        <AxeAccessibility />
        <NetworkModeToggle />
        {children}
      </body>
    </html>
  )
}
